### PR TITLE
Removed redundant src/.jshintrc; added no-unused-vars rule to allow unused args

### PR DESCRIPTION
**Pull request by samdutton**
http://eslint.org/docs/rules/no-unused-vars

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Travis is still not building.

**Comment by samdutton** [comment]
Failing in selenium-webdriver module: https://travis-ci.org/webrtc/samples/jobs/84888949.

Maybe caused by this (??):

> npm WARN engine selenium-webdriver@2.48.0: wanted: {"node":">= 0.12.x"} (current: {"node":"0.10.40","npm":"1.4.28"})

Can't remember — are we keeping to Node 0.10.40 for some reason?

**Comment by KaptenJansson** [comment]
Why isn't the job added to commit here?

**Comment by KaptenJansson** [comment]
Hmm I see a similar failure when trying to run selenium webdriver as well when trying to review #663.

**Comment by samdutton** [comment]
> Why isn't the job added to commit here?

I ran (restarted) a job manually from Travis to attempt to check what was happening.

**Comment by samdutton** [comment]
BTW: I can't see what's wrong with _selenium-webdriver/_base.js_, i.e. why Travis gives `SyntaxError: Unexpected token )` after `vm.` on line 104?

**Comment by KaptenJansson** [comment]
I see a different error locally. Some dependency might be broken, maybe we need to pin some versions. Will give it a try.

**Comment by KaptenJansson** [comment]
FTR I've tried both nodejs 10.x and 12.x, same issue.

**Comment by samdutton** [comment]
Added attempt to fix Travis woes: I removed the reference to selenium-webdriver in package.json, then ran `npm install selenium-webdriver --save-dev`: version is now 2.48.0. No idea if this will help, but worth a try.

@KaptenJansson PTAL

**Comment by weizhl** [comment]
如果想把视频会议的视频都保存到本地服务器上，有什么办法可以解决吗？最好能给个代码，谢谢！

**Comment by samdutton** [comment]
2015-10-20 10:28 GMT+01:00 weizhl notifications@github.com:

> 如果想把视频会议的视频都保存到本地服务器上，有什么办法可以解决吗？最好能给个代码，谢谢！
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/webrtc/samples/pull/665#issuecomment-149492568.

Hi weizhl

This is a repo for WebRTC samples and not the best place to ask questions
about general WebRTC development.

To learn more about WebRTC, I recommend the resources at http://g.co/webrtc. There
are lots of links there to places you can get help, such as StackOverflow and the
discuss-webrtc Google group at https://groups.google.com/forum/#!forum/discuss-webrtc.

**Comment by KaptenJansson** [comment]
> Added attempt to fix Travis woes: I removed the reference to selenium-webdriver in package.json, then ran npm install selenium-webdriver --save-dev: version is now 2.48.0. No idea if this will help, but worth a try.

Selenium webdriver 2.48 and nodejs 12.4 (had to manually compile and install on my workstation due to it blocking external repos which is required in order to get nodejs > version 10 via the package manager) works fine.

**Comment by KaptenJansson** [comment]
Wow the github diff tool does not do a good job of highlighting the difference when doing these kind of changes. LGTM.

**Pull request merged**
