### PR TITLE
Audio knobs

### PR DESCRIPTION
**Pull request by Leeyuryeon**
**Description**

fgfgfgdfg
**Purpose**
dgfdgfgfgf

### CODE REVIEW

**Comment by ErikHellman** [comment]
This PR needs to be rebased. While doing that, please also update the description of what this PR does. 

Since this is a sample, I would expect some comments in the code and/or updated descriptions in the HTML.

**Comment by alvestrand** [comment]
@fippo and @juberti - is this worth salvaging, given that we dont' have a CLA for leeyron?
I note that this PR is from May 5 while the commits are from 2015 - is someone submitting stuff that you authored, Justin?

**Comment by fippo** [comment]
this seems bogus -- commits from a super old PR. Lets close it.

**Comment by fippo** [comment]
if there is something to salvage we should start from https://github.com/webrtc/samples/tree/audio-knobs -- but i am not even sure what @juberti wanted to show here. SDP munging has become a no-no since

**Comment by ErikHellman** [comment]
I'll close the PR. If someone wants to pick up this the branch will still be there. Thanks!

**Pull request closed without merging**
