### PR TITLE
fix audio in Munge SDP example

### PR DESCRIPTION
**Pull request by skorknure**
Currently there is no audio. Just a tiny fix.

### CODE REVIEW

**Comment by samdutton** [comment]
Hi @skorknure – you need to sign the CLA – see [CONTRIBUTING](https://github.com/webrtc/samples/blob/master/CONTRIBUTING.md).

**Comment by juberti** [comment]
lg once CLA signed

**Comment by KaptenJansson** [comment]
@skorknure - please sign the CLA, then we merge this.

**Comment by KaptenJansson** [comment]
Closing due to no response from author and fixed in #522.

**Pull request closed without merging**
