### PR TITLE
Add bandwidth sample page logging when changing bandwidth

### PR DESCRIPTION
**Pull request by KaptenJansson**
**Description**
Add logging of the remoteDescription SDP

**Purpose**
Easier debugging when applying the bandwidth parameter to the SDP

### CODE REVIEW

**Comment by fippo** [comment]
LGTM (not that I am Sam but...)

**Comment by samdutton** [comment]
LVGTM :).

**Comment by kolmodin** [comment]
This prints

```
Applying bandwidth change to setRemoteDescription: [object RTCSessionDescription]
```

I assume you wanted to print the new bandwidth?

**Comment by KaptenJansson** [comment]
Doh, sorry for the mistake, no I wanted to print the SDP after the b=AS parameter has been added.

**Comment by samdutton** [comment]
Prompted me to do #819.

**Pull request merged**
