### PR TITLE
Correct path directory

### PR DESCRIPTION
**Pull request by kamakshidasan**
The file paths seemed to have changed.

### CODE REVIEW

**Comment by kamakshidasan** [comment]
I signed it!

**Review by ErikHellman — APPROVED** [review]
Good catch! I thought I did find them all when I moved the files. Thanks!

**Comment by fippo** [comment]
I don't think an absolute path will work on github pages

**Comment by ErikHellman** [comment]
My bad. I didn't test this properly. 

You're correct @fippo. I'll fix this in a separate PR.

**Pull request merged**
