### PR TITLE
Use onbufferedamountlow, if available, in the data transfer demo

### PR DESCRIPTION
**Pull request by bemasc**
This functionality was just added to Chromium: https://crbug.com/496700

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Could you add a test for this? You can use https://github.com/webrtc/samples/blob/master/src/content/datachannel/filetransfer/js/test.js as a guide.

**Comment by KaptenJansson** [comment]
@bemasc ping

**Comment by KaptenJansson** [comment]
Thanks for the PR btw ;)

**Comment by bemasc** [comment]
I think I'm more inclined to move this change to the filetransfer demo in that case.

**Comment by KaptenJansson** [comment]
Sure, that's fine.

**Comment by KaptenJansson** [comment]
Also test framework introduction can be found at https://github.com/webrtc/samples/tree/master/test.

**Comment by bemasc** [comment]
OK, I've added a test for the datatransfer demo.

**Comment by KaptenJansson** [comment]
LGTM with one nit, I would have preferred to have the test contained in the "test" function rather than calling an outside function (sendData()) however that can be changed if more tests are added.

**Pull request merged**
