### PR TITLE
Clean out samples repo, fix links

### PR DESCRIPTION
**Pull request by juberti**
@jiayl, @chuckhays PTAL

### CODE REVIEW

**Comment by jiayliu** [comment]
Clean up package.json and .gitignore?

**Comment by juberti** [comment]
Cleaned package.json and .gitignore

**Comment by KaptenJansson** [comment]
I removed package.json, there is not point for the samples to use this right?

**Comment by KaptenJansson** [comment]
Also not that a lot of files that are excluded for JSCS but I guess that's due to the files not adhering to the styleguide yet, will file a separate issue for that.

**Comment by jiayliu** [comment]
The benefit of package.json I think is that one can simply 'npm install' to install all the dependencies, without worrying about which exact libraries are needed.
That's why I kept it for apprtc.

**Comment by juberti** [comment]
Agree with Jiayang. package.json restored, Travis passes.

**Comment by juberti** [comment]
PTAL

**Pull request merged**
