### PR TITLE
Compatibility with Android Firefox 47.0

### PR DESCRIPTION
**Pull request by anhr**
I can not Start Recording from the Android Firefox 47.0 because I see
the message: "MediaRecorder is not supported by this browser...". But
this is not true. I have made changing in the function startRecording()
to resolve of the issue.

### CODE REVIEW

**Comment by samdutton** [comment]
Thanks for this — I'm just out of the office but will take a look in a day or two.

BTW: what platform are you on? https://webrtc.github.io/samples/src/content/getusermedia/record works fine for me in Firefox 47.0 on Mac OS X.

**Comment by anhr** [comment]
I have tested on Android (see my first comment). I have used the Samsung Galaxy S5 smartphone

**Comment by KaptenJansson** [comment]
Please fix the [linting issues](https://travis-ci.org/webrtc/samples/jobs/139378162), other than that LGTM.

**Comment by anhr** [comment]
the linting issues has fixed

**Comment by samdutton** [comment]
Thanks @anhr! Missed Android in first comment.

**Pull request merged**
