### PR TITLE
allow adapter.js to be required

### PR DESCRIPTION
**Pull request by fippo**
I'm aware of the discussion in #297 but the pragmatic solution is to just allow it to be require'd.
Anyone who wants to use adapter.js as a module can do it, you don't need to change anything for now, don't need to use browserify, etc.

The console.log output is a bit icky for a module though.

### CODE REVIEW

**Comment by juberti** [comment]
Build failed...

**Comment by fippo** [comment]
Fixed, jshint is a little picky sometimes.

**Comment by juberti** [comment]
Can you resend this to the new repo at webrtc/adapter?

**Comment by fippo** [comment]
only if you promise not to ignore it until it runs into a merge conflict ;-)
(will do)

**Pull request closed without merging**
