### PR TITLE
Add Perfect Negotiation sample

### LINKED ISSUE #1352: Add Perfect Negotiation sample page
In M87, Chromium-based browsers support the Perfect Negotiation pattern - for more info, see [PSA](https://groups.google.com/u/1/g/discuss-webrtc/c/FwCCuFhJHkg).

We should add a web page that illustrates this pattern, similar to [this jsfiddle](https://jsfiddle.net/henbos/7kyrom8b/) (referenced by the PSA).

### PR DESCRIPTION
**Pull request by SCG82**
Fixes #1352

TODO: tests

### CODE REVIEW

**Review by henbos — APPROVED** [review]
This looks like a working demo page based on the jsfiddle. It looks complete to me, is everything working?

I don't know anybody working on the samples page at the moment and you said you were busy, so why don't we merge this and worry about polishing or test coverage later?

**Comment by henbos** [comment]
@fippo Do you want to take a look as well?

**Comment by SCG82** [comment]
Here's a demo: https://mfcobs.com/samples/src/content/peerconnection/perfect-negotiation/

**Comment by fippo** [comment]
i'll defer to @jan-ivar

**Comment by henbos** [comment]
lint checks fail:
```
[14:28:28] 
/home/travis/build/webrtc/samples/src/content/peerconnection/perfect-negotiation/js/main.js
  14:40  error  Strings must use singlequote            quotes
  15:51  error  Strings must use singlequote            quotes
  17:32  error  Strings must use singlequote            quotes
  22:28  error  A space is required after ','           comma-spacing
  22:31  error  A space is required after ','           comma-spacing
  22:38  error  A space is required after ','           comma-spacing
  22:41  error  A space is required after ','           comma-spacing
  42:48  error  A space is required after ','           comma-spacing
  42:51  error  A space is required after ','           comma-spacing
  45:48  error  A space is required after ','           comma-spacing
  45:51  error  A space is required after ','           comma-spacing
  49:46  error  Strings must use singlequote            quotes
  50:48  error  Strings must use singlequote            quotes
  52:42  error  A space is required after ','           comma-spacing
  52:45  error  A space is required after ','           comma-spacing
  52:52  error  A space is required after ','           comma-spacing
  52:55  error  A space is required after ','           comma-spacing
  68:8   error  'peer' is not defined                   no-undef
  75:42  error  A space is required after ','           comma-spacing
  75:44  error  A space is required after ','           comma-spacing
  75:49  error  A space is required after ','           comma-spacing
  75:51  error  A space is required after ','           comma-spacing
  76:45  error  A space is required after ','           comma-spacing
  76:47  error  A space is required after ','           comma-spacing
  76:52  error  A space is required after ','           comma-spacing
  76:54  error  A space is required after ','           comma-spacing
  80:16  error  'swapOnBoth' is defined but never used  no-unused-vars
  82:37  error  Strings must use singlequote            quotes
  83:39  error  Strings must use singlequote            quotes
  85:39  error  Strings must use singlequote            quotes
  86:37  error  Strings must use singlequote            quotes
/home/travis/build/webrtc/samples/src/content/peerconnection/perfect-negotiation/js/peer.js
   11:1   error  Missing JSDoc @return for function                                                                             valid-jsdoc
   11:1   error  Missing JSDoc for parameter 'other'                                                                            valid-jsdoc
   11:1   error  Missing JSDoc for parameter 'polite'                                                                           valid-jsdoc
   11:1   error  Missing JSDoc for parameter 'fail'                                                                             valid-jsdoc
   14:10  error  'peer' is defined but never used                                                                               no-unused-vars
   15:79  error  Strings must use singlequote                                                                                   quotes
   16:3   error  Expected { after 'if' condition                                                                                curly
   17:37  error  There should be no space after '{'                                                                             object-curly-spacing
   17:72  error  There should be no space before '}'                                                                            object-curly-spacing
   22:47  error  Strings must use singlequote                                                                                   quotes
   23:47  error  Strings must use singlequote                                                                                   quotes
   24:47  error  Strings must use singlequote                                                                                   quotes
   26:22  error  Unexpected space(s) after '{'                                                                                  block-spacing
   26:22  error  Statement inside of curly braces should be on next line                                                        brace-style
   26:46  error  Strings must use singlequote                                                                                   quotes
   26:60  error  Strings must use singlequote                                                                                   quotes
   26:83  error  Unexpected space(s) before '}'                                                                                 block-spacing
   26:83  error  Closing curly brace should be on the same line as opening curly brace or on the line after the previous block  brace-style
   29:11  error  Strings must use singlequote                                                                                   quotes
   36:1   error  Expected indentation of 12 spaces but found 10                                                                 indent
   36:53  error  There should be no space after '{'                                                                             object-curly-spacing
   36:86  error  Strings must use singlequote                                                                                   quotes
   36:97  error  There should be no space before '}'                                                                            object-curly-spacing
   38:1   error  Expected indentation of 12 spaces but found 10                                                                 indent
   38:29  error  Strings must use singlequote                                                                                   quotes
   38:38  error  There should be no space after '{'                                                                             object-curly-spacing
   38:71  error  Strings must use singlequote                                                                                   quotes
   38:82  error  There should be no space before '}'                                                                            object-curly-spacing
   42:52  error  Strings must use singlequote                                                                                   quotes
   43:49  error  Strings must use singlequote                                                                                   quotes
   45:49  error  Strings must use singlequote                                                                                   quotes
   48:49  error  Strings must use singlequote                                                                                   quotes
   50:49  error  Strings must use singlequote                                                                                   quotes
   58:11  error  Strings must use singlequote                                                                                   quotes
   62:25  error  Strings must use singlequote                                                                                   quotes
   62:42  error  There should be no space after '{'                                                                             object-curly-spacing
   62:54  error  There should be no space before '}'                                                                            object-curly-spacing
   62:72  error  There should be no space after '{'                                                                             object-curly-spacing
   62:84  error  There should be no space before '}'                                                                            object-curly-spacing
   63:5   error  Split 'let' declarations into multiple statements                                                              one-var
   65:25  error  Strings must use singlequote                                                                                   quotes
   67:13  error  Strings must use singlequote                                                                                   quotes
   68:9   error  'assert_equals' is not defined                                                                                 no-undef
   68:42  error  Strings must use singlequote                                                                                   quotes
   68:52  error  Strings must use singlequote                                                                                   quotes
   69:9   error  'assert_equals' is not defined                                                                                 no-undef
   69:43  error  Strings must use singlequote                                                                                   quotes
   72:9   error  'assert_equals' is not defined                                                                                 no-undef
   72:42  error  Strings must use singlequote                                                                                   quotes
   72:62  error  Strings must use singlequote                                                                                   quotes
   73:9   error  'assert_equals' is not defined                                                                                 no-undef
   73:49  error  Strings must use singlequote                                                                                   quotes
   73:58  error  Strings must use singlequote                                                                                   quotes
   74:21  error  There should be no space after '{'                                                                             object-curly-spacing
   74:56  error  There should be no space before '}'                                                                            object-curly-spacing
   81:31  error  There should be no space after '{'                                                                             object-curly-spacing
   81:39  error  There should be no space after '{'                                                                             object-curly-spacing
   81:69  error  There should be no space before '}'                                                                            object-curly-spacing
   81:71  error  There should be no space before '}'                                                                            object-curly-spacing
   88:15  error  'isStable' is never reassigned. Use 'const' instead                                                            prefer-const
   88:47  error  Strings must use singlequote                                                                                   quotes
   89:35  error  Strings must use singlequote                                                                                   quotes
   91:33  error  Strings must use singlequote                                                                                   quotes
   93:17  error  Strings must use singlequote                                                                                   quotes
   96:35  error  Strings must use singlequote                                                                                   quotes
   99:15  error  Strings must use singlequote                                                                                   quotes
   99:43  error  Strings must use singlequote                                                                                   quotes
  102:35  error  Strings must use singlequote                                                                                   quotes
  103:13  error  'assert_equals' is not defined                                                                                 no-undef
  103:46  error  Strings must use singlequote                                                                                   quotes
  103:67  error  Strings must use singlequote                                                                                   quotes
  104:13  error  'assert_equals' is not defined                                                                                 no-undef
  104:54  error  Strings must use singlequote                                                                                   quotes
  104:63  error  Strings must use singlequote                                                                                   quotes
  105:17  error  Strings must use singlequote                                                                                   quotes
  107:13  error  'assert_equals' is not defined                                                                                 no-undef
  107:46  error  Strings must use singlequote                                                                                   quotes
  107:56  error  Strings must use singlequote                                                                                   quotes
  108:13  error  'assert_equals' is not defined                                                                                 no-undef
  108:53  error  Strings must use singlequote                                                                                   quotes
  108:63  error  Strings must use singlequote                                                                                   quotes
  109:25  error  There should be no space after '{'                                                                             object-curly-spacing
  109:60  error  There should be no space before '}'                                                                            object-curly-spacing
  111:13  error  'assert_equals' is not defined                                                                                 no-undef
  111:54  error  Strings must use singlequote                                                                                   quotes
  111:64  error  Strings must use singlequote                                                                                   quotes
  112:13  error  'assert_equals' is not defined                                                                                 no-undef
  112:46  error  Strings must use singlequote                                                                                   quotes
  112:56  error  Strings must use singlequote                                                                                   quotes
  113:40  error  Strings must use singlequote                                                                                   quotes
  119:13  error  Expected { after 'if' condition                                                                                curly
  123:31  error  There should be no space after '{'                                                                             object-curly-spacing
  123:74  error  There should be no space before '}'                                                                            object-curly-spacing
```

Could these be addressed? Mostly style guide complaints

**Comment by SCG82** [comment]
Fixed lint issues

**Comment by henbos** [comment]
Thanks, let's merge? :D

**Comment by henbos** [comment]
It's now published at https://webrtc.github.io/samples/src/content/peerconnection/perfect-negotiation/.

I had Chrome M86 running, which doesn't have the Perfect Negotiation bug fixes and was able to hit a race where the page stopped negotiating (and remote video disappeared). The relevant fixes is in M87, which should be rolling out at the moment, but I didn't have it yet.

So I ran Chrome Canary (89.0.4337.0) and it worked like a charm. I was unable to make it get stuck.

**Pull request merged**
