### PR TITLE
use mediaDevices and show alert with error

### PR DESCRIPTION
**Pull request by nils-ohlmeier**
**Description**
Show the same gUM error alert message as in the peerconnection example.
Also update gUM request to the new promise based version under mediaDevices.

**Purpose**
Align peerconnection and gUM examples to show the same behavior.

### CODE REVIEW

**Comment by fippo** [comment]
@jan-ivar do you recall why you added a 200ms timeout? Probably to give the stream time to stop, is that still necessary?

**Comment by nils-ohlmeier** [comment]
I signed it (company name: Mozilla)!

**Comment by nils-ohlmeier** [comment]
@fippo seems to be working for me on Fx 48 without the 200ms extra delay

**Comment by jan-ivar** [comment]
@fippo, yeah that was why, w/persistent permission. Seems to have been fixed. Verified in 43 and 46.

**Comment by KaptenJansson** [comment]
@nils-ohlmeier did you sign it as an individual or corporate? If corporate your email need to belong to the google group tied to the corporate agreement. Also make sure your git commits has the correct email.

**Comment by nils-ohlmeier** [comment]
@KaptenJansson I thought doing it corporate would the easiest, but aligning all of that seems to be a lot of effort. So instead I just signed the individual CLA.

**Comment by nils-ohlmeier** [comment]
So apparently my github email needs to align with gmail address. Which is not the case. What is the recommended solution for that?

**Comment by KaptenJansson** [comment]
Sign the CLA with the email used in your git commits.

**Comment by KaptenJansson** [comment]
Ping

**Pull request merged**
