### PR TITLE
record: Correct AV1 MIME type

### PR DESCRIPTION
**Pull request by rosetta-jpn**
The correct AV1 MIME is "av01".

### CODE REVIEW

**Comment by alvestrand** [comment]
The registered media type for AV1 at IANA is AV1: https://www.iana.org/assignments/media-types/video/AV1

Where did you get a reference saying "AV01" from?

**Comment by rosetta-jpn** [comment]
The media type should be used for real time streaming.

> Applications which use this media:
> Video over IP, video conferencing, video streaming.

I think, for Media Streaming API, the regular MIME type should be used.
https://aomediacodec.github.io/av1-isobmff/#av1sampleentry-section

**Comment by rosetta-jpn** [comment]
I searched more. 
So there are two ways how to specify the mime, mime and mime+codecs. 
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/mimeType

(1) With MIME only, `video/av1` should be used.

See https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/mimeType
> The media type strings are standardized by the Internet Assigned Numbers Authority (IANA). For their official list of defined media type strings, see the article [Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml) on the IANA site.

(2) With MIME + codecs, 'video/webm; codecs="av01"' should be used.

See https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#av1


I will clarify the commit message.

**Comment by rosetta-jpn** [comment]
I created a new pull request https://github.com/webrtc/samples/pull/1611.

**Pull request closed without merging**
