### PR TITLE
more useful chrome flags

### PR DESCRIPTION
**Pull request by fippo**
@KaptenJansson I think we should move the selenium lib into a npm package.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Yes, I will do that this week.

**Comment by KaptenJansson** [comment]
FTR What's the reason behind enabling these flags?

**Comment by fippo** [comment]
mute-audio is useful for local testing unless you like the beeps. The other two seemed like good common practice from http://peter.sh/experiments/chromium-command-line-switches/

**Comment by KaptenJansson** [comment]
I cannot find the no-process-singleton-dialog flag at http://peter.sh/experiments/chromium-command-line-switches/. I googled it and basically it seems like it suppresses a warning if another instance is using the profile?

While we are at good testing practices, maybe we should include --no-first-run --no-default-browser-check as well?

**Comment by fippo** [comment]
hrm... I wonder where I found the flag but peter.sh gave me funny versions in the last days -- some showing the big TODO for tommi, other that did not. But yes, suppressing that warning seemed like a good best practice for testing.

+1 on -no-first-run and -no-default-browser-check, even though those mostly affect some ui bars which are ignored anyway.

Will make a new PR in the utilities repo. Maybe @phoglund knows some more useful flags offhand?

**Comment by fippo** [comment]
see utilities repo

**Pull request closed without merging**
