### PR TITLE
change-codecs: display actual codec

### PR DESCRIPTION
**Pull request by fippo**
which might be useful on android. See
  https://bugs.chromium.org/p/chromium/issues/detail?id=1147514

### CODE REVIEW

**Comment by fippo** [comment]
@henbos @alvestrand  PTAL and explain me why why there is no [sdpFmtpLine](https://w3c.github.io/webrtc-stats/#dom-rtccodecstats) on the codec stats so I can identify which dialect of vp9/h264 I am using

**Comment by alvestrand** [comment]
The missing fmtp line is a bug. We need to fix that.

**Comment by fippo** [comment]
bug for tracking: https://bugs.chromium.org/p/webrtc/issues/detail?id=12181

**Comment by henbos** [comment]
Also not sure if we collect RTCCodecStats per m= section or not

**Comment by fippo** [comment]
Updated to include sdpFmtpLine if present ;-)

**Review by henbos — APPROVED** [review]

**Comment by henbos** [comment]
@fippo this looks good to me, is this ready to be merged or is there an issue with the sdpFmtpLine etc?

**Comment by henbos** [comment]
To be merged when travis is green!

**Pull request merged**
