### PR TITLE
crop: update to use frame copy constructor

### PR DESCRIPTION
**Pull request by fippo**
with visibleRect. See
  https://github.com/w3c/webcodecs/issues/281
(but not the small differences between the proposal and the actual api)

### CODE REVIEW

**Comment by fippo** [comment]
@dogben PTAL

**Comment by fippo** [comment]
not really this sample but I wonder if we need to explain [sample aligned](https://w3c.github.io/webcodecs/#videoframe-copyto-options) which creates some restrictions on the x/y (making them divisible by 4 works from what I can see)

**Review by dogben — APPROVED** [review]

**Comment by dogben** [comment]
> not really this sample but I wonder if we need to explain [sample aligned](https://w3c.github.io/webcodecs/#videoframe-copyto-options) which creates some restrictions on the x/y (making them divisible by 4 works from what I can see)

Agree it's not an ideal API. I think if the crop/scale constructor were extended to handle all CanvasImageSources then we would almost necessarily need to drop the sample-aligned requirement. I'm hoping that's the direction we'll head in; otherwise we may want to have accessors for alignmentX/Y.

**Comment by dogben** [comment]
> not really this sample but I wonder if we need to explain [sample aligned](https://w3c.github.io/webcodecs/#videoframe-copyto-options) which creates some restrictions on the x/y (making them divisible by 4 works from what I can see)

Forgot to say -- I think it's supposed to work if they're divisible by 2. If you're seeing different behavior, it may be worth filing a bug.

**Comment by fippo** [comment]
2 works too, thank you!

**Pull request merged**
