### PR TITLE
support firefox in constraints demo

### PR DESCRIPTION
**Pull request by fippo**
when createOffer is called with only one argument, firefox interprets this a offerOptions and returns a promise so the callback is never called.

I'll also try to fix getStats while i'm in that file :-)

### CODE REVIEW

**Comment by fippo** [comment]
uhm... since https://github.com/webrtc/samples/blob/master/src/content/peerconnection/constraints/js/main.js#L222
is working around code which (I think) is from Chrome 25 almost two years ago... any objections against completly rewriting this demo in a spec-compliant way?

**Comment by fippo** [comment]
https://fippo.github.io/webrtc/src/content/peerconnection/constraints/
-- almost done. Just need to figure out how to get the peer ip and port in Firefox. 
For chrome I know how to do that (without making @juberti's eyes hurt even).

@milkypostman I think that's going to fix #526 :-)

**Comment by KaptenJansson** [comment]
>https://fippo.github.io/webrtc/src/content/peerconnection/constraints/
-- almost done. Just need to figure out how to get the peer ip and port in Firefox. 
For chrome I know how to do that (without making @juberti's eyes hurt even).


Nice work! I noticed the constraints page allows the user to start arbitrary peerconnections by spamming the connect button ;). Created issue #552 for this. 

Do you want to add anything more to this pull request before merge?

**Comment by fippo** [comment]
Ended up rewriting the demo. The only thing missing is figuring out the peer's ip address. I want a separate PR for this... actually tempted to demo it in https://github.com/webrtc/apprtc/pull/99 instead :-)

**Comment by fippo** [comment]
meta question: should this be renamed/repurposed to be only about stats? we have the resolution demo for resolutions which afaics only lacks a framerate setting

**Comment by jan-ivar** [comment]
I'm guessing the reason constraints cane be changed here is to test various bitrate loads, which presumably is still useful.

**Comment by fippo** [comment]
and the peer ip is back. Looking for the remotecandidate after figuring out the active pair didn't require any backward compat hacks thankfully!

**Comment by KaptenJansson** [comment]
LGTM, @samdutton WDYT?

**Comment by samdutton** [comment]
Nice one. LGTM.

**Comment by samdutton** [comment]
Pushed to gh-pages.

**Pull request merged**
