### PR TITLE
Use wait+promise for videoelements

### PR DESCRIPTION
**Pull request by KaptenJansson**
Lets see if this approach fixes the flake for real.

It's funny that it only flakes out after I merge it to the master branch.........

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Just realized it was already at 30 seconds and I bumped to 1 minute. Does it really take that long to enumerate devices?

**Comment by KaptenJansson** [comment]
Trying to merge this and pray to the selenium and firefox gods ;).

**Comment by KaptenJansson** [comment]
Yay it's green!

**Comment by jan-ivar** [comment]
> Just realized it was already at 30 seconds and I bumped to 1 minute. Does it really take that long to enumerate devices?

That seems way excessive. Have you looked at using [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)? (I haven't tried it).

**Comment by KaptenJansson** [comment]
Yes it was and it did not work, it does not seem like the timeout is actually enforced as it failed before the timeout was reached. Anyway I've removed the timeout altogether and use `wait()` and `until()` together instead.

**Comment by samdutton** [comment]
FWIW I built a MutationObserver sample here: simpl.info/mo.

**Comment by jan-ivar** [comment]
sweet!

**Pull request merged**
