### PR TITLE
add test for multiple demo

### PR DESCRIPTION
**Pull request by fippo**
having a test would have probably prevented me from breaking things fixed in #662 
Not sure what to test for the states sample.

### CODE REVIEW

**Comment by fippo** [comment]
hrm. no travis checks? samples repo is missing from https://travis-ci.org/webrtc @samdutton @KaptenJansson

**Comment by KaptenJansson** [comment]
Hmm. It's active according to the travis settings but it still does not trigger on PR nor is it visible on  https://travis-ci.org/webrtc

**Comment by KaptenJansson** [comment]
I also see a request in travis under the Request tab, but no job ID is attached to it:
`2 minutes ago #663 587c638 add test for multiple demo - github pages branch`

**Comment by KaptenJansson** [comment]
Ran this locally and saw 4 eslint errors:

> webrtc-samples@1.0.0 test /mnt/storage/src/github/samples
> grunt && test/run-tests

Running "csslint:strict" (csslint) task

> > 16 files lint free.

Running "csslint:lax" (csslint) task

> > 16 files lint free.

Running "htmlhint:html1" (htmlhint) task

> > 23 files lint free.

Running "eslint:target" (eslint) task

/mnt/storage/src/github/samples/src/content/devices/input-output/js/test.js
   20:5  error  Expected indentation of 2 space characters but found 4  indent
   22:5  error  Expected indentation of 2 space characters but found 4  indent
   24:5  error  Expected indentation of 2 space characters but found 4  indent
  132:3  error  Expected indentation of 0 space characters but found 2  indent

The whole test is indented 2 spaces to much, most likely due to the linebreak in the test function name.

**Comment by KaptenJansson** [comment]
Hmm, just realized that error is not even related to your change but are you running eslint locally?

**Comment by KaptenJansson** [comment]
Also webdriver fails to start for me, tried updating nodej.js and webdriver to the latest version but it fails with undefined, vlog(2,0) something. Need to figure out why.

**Comment by samdutton** [comment]
> are you running eslint locally?

Yes. 

For some reason ESLint is not finding any errors when I use SublimeLinter — but running `grunt eslint` from the command line gives the errors above :(. 

Can't for the life of me figure out what's going on. Working on it...

**Comment by fippo** [comment]
@samdutton i'd bet on ignoring the config and using the default one...

**Comment by samdutton** [comment]
@fippo Yes — that's what I thought, but can't for the life of me work out why that's happening...

Using JS Beautifier I re-indented _input-output/js/test.js_. ESLint now seems happy in Sublime and from the command line. Pushed the update.

**Comment by KaptenJansson** [comment]
I will try to merge this one as it was created when samples/ was in a bad state, lets hope the push results in a travis test run and that it succeeds, will revert otherwise.

**Comment by KaptenJansson** [comment]
Yay the test passed ;)

**Pull request merged**
