### PR TITLE
use eslint-config-webrtc

### PR DESCRIPTION
**Pull request by fippo**
same as https://github.com/webrtc/adapter/pull/284

### CODE REVIEW

**Comment by fippo** [comment]
looks like firefox beta doesn't like selenium-webdriver anymore :-/

**Comment by KaptenJansson** [comment]
Yeah that is strange, disable?

**Comment by fippo** [comment]
can you try bumping it 2-3 times?

**Comment by KaptenJansson** [comment]
Done, but I've already tried in a different PR a few times

**Comment by KaptenJansson** [comment]
LGTM

**Comment by KaptenJansson** [comment]
I will deal with the FF beta failure.

**Pull request merged**
