### PR TITLE
Source demo - Move to devices folder, rename to input-output, fix style

### PR DESCRIPTION
**Pull request by KaptenJansson**
Addresses https://github.com/webrtc/samples/pull/539#issuecomment-119581072

Serving at http://kaptenjansson.github.io/samples/src/content/devices/input-output/

### CODE REVIEW

**Comment by samdutton** [comment]
LGTM

**Comment by KaptenJansson** [comment]
Now serving on gh-pages (also fixed a stupid mistake https://github.com/webrtc/samples/commit/1759b31b8ca3c72379187952f190c5a8079632c5 ).

**Comment by jan-ivar** [comment]
http://webrtc.github.io/samples/src/content/getusermedia/source just 404ed on me, which led me here. This looks great, but could we leave a redirect at the old location? Links and the internet and all that.

**Comment by jan-ivar** [comment]
@KaptenJansson Also maybe only show the "*Enable experimental support in Chrome 45.0.2441.x" if `webrtcDetectedBrowser == 'chrome'`?

**Comment by jan-ivar** [comment]
Also you forgot to update the "View source on GitHub" link. 404.

**Comment by samdutton** [comment]
Ah – good point.

Looks like GitHub Pages redirects are possible:
help.github.com/articles/redirects-on-github-pages.

**Comment by KaptenJansson** [comment]
Github pages redirects look like but it requires a plugin. Just keep a
simple HTML redirect for now?

**Comment by samdutton** [comment]
Yup. Shouldn't have *too* many of these.

**Pull request merged**
