### PR TITLE
Convert samples code to ES6

### PR DESCRIPTION
**Pull request by ErikHellman**
**Description**
A first step in converting the samples code to ES6.

### CODE REVIEW

**Comment by ErikHellman** [comment]
The tests became flaky with these changes. 

Looking into that.

**Comment by samdutton** [comment]
Wow! Nice work — I'll take a look.

**Comment by fippo** [comment]
I think this is not flakyness. I've seen quite some issues recently when trying to access ES6 let/const variables from a selenium executeScript. Basically it looks like the geckodriver scope can not access those variables. The console scope can.

This is specific to geckodriver, chromedriver has no such issues.

**Comment by ErikHellman** [comment]
closing this and will make this changes incrementally instead.

**Pull request closed without merging**
