### PR TITLE
Video processing sample: remove workarounds

### PR DESCRIPTION
**Pull request by dogben**
Remove workarounds for bugs and API changes in older versions of Chrome.

### CODE REVIEW

**Review by KaptenJansson — APPROVED** [review]
LGTM

**Comment by vicdos2109-ai** [comment]
src/content/devices/input-output

**Comment by vicdos2109-ai** [comment]
2src/content/getusermedia/gum

**Comment by vicdos2109-ai** [comment]
122

**Comment by vicdos2109-ai** [comment]
ssh -p 122 admin@HOSTNAME

**Pull request merged**
