### PR TITLE
Added ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by samdutton**
Re  #756.

We can agree the template for /samples here, then create versions for the other WebRTC repos.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Maybe move browser version to the top like we have in crbug.com?

**Comment by KaptenJansson** [comment]
Also, I think we should add a pull request template with Description and either Purpose, Justification or Why headers.

**Comment by samdutton** [comment]
Good idea @KaptenJansson — tweaked and added.

**Comment by KaptenJansson** [comment]
LGTM

**Pull request merged**
