### PR TITLE
Added an update_dependencies.sh script.

### PR DESCRIPTION
**Pull request by alvestrand**
This will pull in the latest version of adapter.js and push it
into the js include directory.

### CODE REVIEW

**Comment by alvestrand** [comment]
@juberti @KaptenJansson this is a very pedestrian method of importing adapter.js. It allows us to easily pin to a version if desired, and encodes where we pull it from - but it does not break anything automatically on adapter.js updates, which is good.

Thoughts?

**Comment by KaptenJansson** [comment]
Should we assume everyone is running in a shell environment? I think a python script is a more universal approach.

**Comment by alvestrand** [comment]
I think we can safely assume that anyone who updates the dependencies has access to a shell environment. I don't want to call the NPM command line from python - I don't know how portable that command line is.

**Comment by KaptenJansson** [comment]
Also, we would not need to have adapter.js in the master repo? Or do you want it there for consistency between master and gh-pages?

If the latter it would be nice if npm install would run the script automagically.

**Comment by KaptenJansson** [comment]
npm scripts: https://docs.npmjs.com/misc/scripts

**Comment by alvestrand** [comment]
The reasons for doing a copy and checking in the result:
- Allows us to serve out of gh-pages
- Allows anyone who checks out the demos to run them without running npm install
But there's no real reason for doing npm install without also copying into src/js/adapter.js.

New version, fully npm-scriptified. Anyone who does npm install will also be updating adapter.js.

**Comment by KaptenJansson** [comment]
Perfect, I think we should also update README.md instructing users to run npm install.

**Comment by KaptenJansson** [comment]
On second thought it's only necessary if you want the latest which potentially could be a different version.   Maybe we do not have to instruct the users about, rather just inform about it.

**Comment by KaptenJansson** [comment]
LGTM with nit in previous comment.

**Comment by alvestrand** [comment]
A note in CONTRIBUTING.js seems appropriate.

**Comment by KaptenJansson** [comment]
LGTM

**Comment by KaptenJansson** [comment]
@alvestrand Should we perhaps do this for apprtc as well?

**Pull request merged**
