### PR TITLE
disable gather button while gathering, fixes #830

### LINKED ISSUE #830: "Uncaught TypeError: Cannot read property 'close' of null" seen in /trickle-ice/ page
**Browsers and versions affected**
M55 Canary 55.0.2868.0 in Win 10

**Description**
"Uncaught TypeError: Cannot read property 'close' of null" thrown in /trickle-ice/ page

**Steps to reproduce**
1. Open https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ in Chrome
2. Keeping the ICE server as the default STUN, change the ICE options as
    - uncheck 'Gather IPv6 candidates' 
    - uncheck 'Gather RTCP candidates'
3. Click 'Gather candidates'
4. Now, check 'none' for IceTransports value and gather candidates again
5. Repeat steps 2, 3, 4 with various combinations of ICE options till you see the error in the JS console

**Expected results**
No JS errors should be seen 

**Actual results**
Uncaught TypeError: Cannot read property 'close' of null thrown 

CC: @KaptenJansson

### PR DESCRIPTION
**Pull request by fippo**
see discussion in #830

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Ping @alvestrand

**Comment by alvestrand** [comment]
lgtm, but needs rebase.

**Comment by fippo** [comment]
can someone hit the "restart" button on travis? I can but it does nothing.
I wish "retest this please" worked :-/

**Comment by KaptenJansson** [comment]
Restart pressed.

**Pull request merged**
