### PR TITLE
Issue 961 - Updating the test file with a title and text

### PR DESCRIPTION
**Pull request by rantonysamy**
As requested in the issue 961, https://github.com/webrtc/samples/issues/961 Updating the test page with a title.

**Description**
Adding a title and a link to go back to the previous page

**Purpose**
If user ends up in this page, It gives no clue about the test. so adding a title, and a link to go back to the previous page.

### CODE REVIEW

**Review by KaptenJansson — CHANGES_REQUESTED** [review]
Could you make it look like the other samples by applying the the same CSS styles etc?

**Comment by fippo** [comment]
also indent (makes me wonder if there is htmllint because arguments about indent are the worst :-))

**Comment by KaptenJansson** [comment]
Yes please fix indents and it's weird that HTMLhint does not trigger on this, might be config issue, will check.

**Comment by KaptenJansson** [comment]
https://github.com/yaniswang/HTMLHint/wiki/Rules indicates it does not check for indentation.....

**Comment by KaptenJansson** [comment]
https://github.com/htmllint/htmllint/wiki/Options has indent checks. Will try it out.

**Comment by fippo** [comment]
@samdutton do you have an idea why htmllint does not behave as we expect?

**Comment by samdutton** [comment]
@fippo @KaptenJansson I don't get any errors reported by HTMLHint for the HTML in this file, but I do get an error that the CSS rules aren't in alphabetical order.

**Comment by fippo** [comment]
oh so there is htmlhint and htmllint... splendid!

**Comment by KaptenJansson** [comment]
@rantonysamy  please do another pass here and try to get the indendation correct.

**Comment by KaptenJansson** [comment]
Ping

**Pull request merged**
