### PR TITLE
Update the extension to v0.2.1.1

### PR DESCRIPTION
**Pull request by guoweis**

### CODE REVIEW

**Comment by guoweis** [comment]
I signed it!

**Comment by KaptenJansson** [comment]
guoweis, could you add your webrtc address to your github account? I think that's why the CLA bot fails.

**Comment by KaptenJansson** [comment]
Also pls fix the merge conflict.

LGTM after that.

**Comment by guoweis** [comment]
I did have the account but maybe because it's not primary? changed now.
How do I see what the conflict is?

**Comment by KaptenJansson** [comment]
if you try to merge master from this repo into your branch you should see the issue.

**Comment by KaptenJansson** [comment]
@guoweis ping

**Pull request closed without merging**
