### PR TITLE
e2ee: polyfill RTCEncoded(Audio|Video)Frame.getMetadata()

### PR DESCRIPTION
**Pull request by fippo**
For the encoded video frame this is an incomplete polyfill since
the additional properties would have to be parsed from the additionalData
and depends on the codec used.

### CODE REVIEW

**Comment by fippo** [comment]
will test in tomorrows canary. I haven't seen much of a need for additonalData yet so I am not particularly keen on polyfilling that one ;-)

**Comment by fippo** [comment]
almost... `window` is not defined in a worker so one has to use `self`

**Review by guidou — APPROVED** [review]

**Comment by fippo** [comment]
this doesn't work since RTCEncodedAudioFrame is not defined in the worker.

**Comment by fippo** [comment]
@foolip: we need your IDL wisdom. Should RTCEncodedAudioFrame and RTCEncodedVideoFrame exist in the worker scope? They can clearly be used...

**Comment by foolip** [comment]
https://github.com/alvestrand/webrtc-media-streams/blob/master/explainer.md#api is missing the require `Exposed` extended attribute, and I can't tell from the rest of the IDL what's intended here. @alvestrand should these interfaces be exposed to workers?

**Comment by fippo** [comment]
even if we do that, we can't do the polyfill in M83. Pity but... we found a potential spec bug and doing the polyfill at runtime can be considered another transform.

**Comment by fippo** [comment]
updated the code here and filed a (pre-)spec issue

**Comment by alvestrand** [comment]
Also nicely illustrates that chaining transforms can be useful!

**Pull request merged**
