### PR TITLE
Change trace() call to console.log()

### LINKED ISSUE #812: Uncaught ReferenceError: trace is not defined thrown in the captureStream() page
**Browsers and versions affected**
Chrome M53 53.0.2785.45, M54 54.0.2817.0 
Mac 10.11.6, Android N Nexus 5X

**Description**
Uncaught ReferenceError: trace is not defined thrown in the captureStream() page

**Steps to reproduce**
1. Open https://webrtc.github.io/samples/src/content/capture/video-video/ in Chrome
2. Inspect the JS console for any JS errors

**Expected results**
No JS errors should be seen

**Actual results**
Uncaught ReferenceError: trace is not defined
leftVideo.onplay @ main.js:28
JS error thrown. Screenshot attached. 

CC: @KaptenJansson @samdutton 

screen shot 2016-08-03 at 1 50 12 pm

### PR DESCRIPTION
**Pull request by samdutton**
**Description**
Use `console.log()` to avoid need to use `trace()` code.

**Purpose**
Fix #812.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
LGTM, Wonder why I do not see the squash option for merging?

**Comment by samdutton** [comment]
I noticed the same :(. Sorry it's such a mess!

**Comment by samdutton** [comment]
Ah — just realised, you get it on clicking Merge.

**Comment by KaptenJansson** [comment]
I see ;)

**Pull request merged**
