### PR TITLE
fix favicon

### LINKED ISSUE #867: 404 error in peerconnection/pr-answer sample page
**Browsers and versions affected**
Chrome : 57.0.2984.0 / 9202.0.0 dev
OS: Chrome and Linux

**Steps to reproduce**
0. Browse to https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Check if the local video is seen in the left pane
3. Click "Accept"
4. Click "Hangup"

**Expected results**
- Local video is displayed in the left pane
- Remote video is displayed after clicking "Accept"
- Remote video is blank after clicking "hangup"
- There should no errors in javascript console

**Actual results**
- Local video is displayed in the left pane
- Remote video is displayed after clicking "Accept"
- Remote video is blank after clicking "hangup"
-  javascript console shows " GET https://webrtc.github.io/favicon.ico 404 (Not Found)"

[pc_pranswer_js_logs.txt](https://github.com/webrtc/samples/files/720388/pc_pranswer_js_logs.txt)

### PR DESCRIPTION
**Pull request by fippo**
closes #867 

(the demo is in dire need for a @samdutton though :-))

### CODE REVIEW

**Comment by samdutton** [comment]
LGTM, but we should use a Web App manifest.

I think the code here for icons is pretty much as it should be (and what we should imitate): view-source:https://codelabs.developers.google.com/io2016

**Comment by KaptenJansson** [comment]
So what's next here?

**Comment by fippo** [comment]
<3 @googlebot but I signed it ;-)

**Comment by samdutton** [comment]
@fippo Seems to be whingeing about CLA :/.

> So what's next here?

I'd say merge this PR, then imitate code like that used on Paul Lewis's [Biograf](https://biograf-155113.appspot-preview.com/) demo: the head element contents, and the manifest. We could follow the example of the codelab site I suggested above, but the Biograf icon code is simpler and adequate for the WebRTC samples.

**Comment by fippo** [comment]
@samdutton the bot didn't like you merging gh-pages into this. Which is somewhat silly ;-)

@KaptenJansson ping.

**Comment by KaptenJansson** [comment]
Merging CL with "CLA no" which is due to gh-pages branch that was merged earlier which has commits from people not in this PR (the commits are already in gh-pages though obviously)

**Pull request merged**
