### PR TITLE
Merge back missing commit "preliminary update of adapter with edge support"

### PR DESCRIPTION
**Pull request by KaptenJansson**
Prep work for #668. Next up is to merge adapter 0.2.5, will do in a separate PR.

@samdutton I wonder if more commits are missing from master, I will try to take a look on Monday. The master to gh-pages move is a bit of a mess ;)

@fippo FYI.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
@fippo and @samdutton add LGTM here please to make the googlebot happy ;).

**Comment by fippo** [comment]
LGTM

**Comment by samdutton** [comment]
Not knowledgable about details but code LGTM.

**Comment by samdutton** [comment]
>  I wonder if more commits are missing from master

Hmm... In theory I got master retrieved at the point where it was deleted :(. Maybe commits from other branches got lost?

Just writing a post mortem of move to gh-pages, and how to do it better.

**Pull request merged**
