### PR TITLE
travis: allow failure in FF

### PR DESCRIPTION
**Pull request by fippo**
FF52 is not behaving well on travis so allow failure :-/

@KaptenJansson can you take another look at #881 and #883 please?

### CODE REVIEW

**Comment by fippo** [comment]
ugh. https://github.com/webrtc/utilities/pull/26 should help.

**Comment by fippo** [comment]
so it looks like we're better now but things stil fail :-/

**Comment by fippo** [comment]
FF beta still fails like this in a number of tests:
not ok 34 InvalidArgumentError: Expected [object Undefined] undefined to be a string

i suspect a geckodriver/selenium issue :-/

**Comment by fippo** [comment]
will probably need to update / pin geckodriver and selenium-webdriver in utilities. Or: make a master dev-dependency that has both things as dependencies

**Comment by aullman** [comment]
@fippo am I right that adding that pulseaudio thing fixed the issue with getUserMedia timing out?

**Comment by aullman** [comment]
Oh wow, that totally worked. Good find!

**Comment by fippo** [comment]
current status is: re-enable firefox after starting pulseaudio. Versions are still pinned.

**Comment by KaptenJansson** [comment]
LGTM

**Pull request merged**
