### PR TITLE
test: try three times

### PR DESCRIPTION
**Pull request by fippo**
hoping that this increases stability

### CODE REVIEW

**Comment by alvestrand** [comment]
The experience in WebRTC and Chrome is that this decreases flakiness to a level where it hides code that is actually wrong and needs to be fixed.....  I suspect we'd be better off in many cases by disabling the corresponding tests and filing bugs on them.

**Comment by fippo** [comment]
to be fair, chromium CQ will automatically retry once, no?

**Comment by alvestrand** [comment]
actually I believe Chromium CQ will try 3 times on each bot run, and
reschedule the bot run if it fails, so at least 6 times.
The list of flaky tests is *horribly* long in Chrome, which is a reason why
I don't want to slide towards that state.

**Comment by fippo** [comment]
true. I'll try to make this work with a single driver instance - creating and closing so many instances may well overload the CI bots

**Comment by fippo** [comment]
closing for now

**Pull request closed without merging**
