### PR TITLE
add selenium tests for munge-sdp and trickle ice pages

### PR DESCRIPTION
**Pull request by fippo**
basically #574 without all the commits trying to figure out what went wrong.

* fixes the shared profile issue created by moving stuff to the lib
* adds tests for munge-sdp and trickle-ice
* makes the gum demo not wait for one second but until window.stream is defined (i think this polls every 500ms)

### CODE REVIEW

**Comment by fippo** [comment]
the test seems flaky. Also spams alot of Firefox windows locally which I think is related overriding the profile created with "integrationtest" in https://github.com/DamonOehlman/travis-multirunner/blob/master/start-firefox.sh#L25

**Comment by fippo** [comment]
the "fix" in the last commit is odd. Why is this only a problem with the last test run?!

**Comment by KaptenJansson** [comment]
Also why is firefox-unstable hanging on the first test? I traced it to the `driver.get('file://' + process.cwd() +
      '/src/content/getusermedia/gum/index.html')` step in the gum test. The .then Promise method is never triggered it seems.

**Comment by KaptenJansson** [comment]
LGTM

**Pull request merged**
