### PR TITLE
preliminary update of adapter with edge support

### PR DESCRIPTION
**Pull request by fippo**
pending some discussion of whether ORTC should be shimmed in adapter I would like the demos to work in Edge. This makes a bunch of them work:
 * pc1
 * audio
 * multiple
 * munge-sdp (kind of... sdp munging is not supported. There is a limit how far I want to go)
 * constraints
 * states
 * trickle-ice (need to recheck the TURN support in Edge)

### CODE REVIEW

**Comment by alvestrand** [comment]
My biggest issue is that it increases the size of adapter.js from 487 lines to more than 1500, and the >1000 added lines can't be tested by our current CI solution.

Are there any solutions that avoid this bloat, without destroying the simple "script src=adapter.js" usage?

I'd even be willing to consider solutions that generate the adapter.js file from an (npm-included) ortc-adapter.js file and a non-edge-adapter.js file....

**Comment by jan-ivar** [comment]
Getting ORTC working with 1000 lines of code is actually quite a feat, considering other attempts at least twice the size.

**Comment by fippo** [comment]
I agree that a small-module approach would be better. I'll see if I can generate a browserified adapter that is based on a adapter+edge module which requires webrtc-adapter-test and adds Edge support.

WRT to testing the samples this doesn't make this worse. We have Chrome and Edge covered and Edge can consider Edge experimental.  Actually I just noticed that the munge-demo broke since it now uses datachannels so I need to investigate whether the issue I ran into with the edge webdriver is still a thing...

**Comment by fippo** [comment]
I just did an experiment:
1) moved all ORTC code to adapter-edge.js
2)  required adapter in adapter-edge, set module.exports to that
3) made attachMediaStream a function on window to break out of the module. Same for trace.
4) Browserified adapter-edge, put it into this repo and ran the tests
5) watched the device test fail because it queries webrtcDetectedBrowser from JS.

I think trace() does not belong into adapter.js, it is something the samples should share. attachMediaStream and reattachMediaStream should disappear as well imo. I can make it happen for the samples. And the test should be easy to fix. Does that look like the way to move this forward for the samples?
I think there is still some work to be done in https://github.com/webrtc/adapter/pull/136 but that is a different issue :-)

**Comment by samdutton** [comment]
>
> I think trace() does not belong into adapter.js, it is something the
> samples should share.


I agree. What do you think is best — just include the code in a separate
.js file?


> attachMediaStream and reattachMediaStream should disappear as well imo.


Agree. As it is, the code is more complex than without these functions.


> I can make it happen for the samples.
>

Yes please!

**Comment by samdutton** [comment]
@KaptenJansson @juberti:  Any objections to merging this? 

I don't have Edge to test with at the moment.

**Comment by KaptenJansson** [comment]
@fippo WRT to 1, are you planning on committing this?
WRT to 5, are you planning on adding a work around for this? Or do you think we should handle that test differently?

**Pull request merged**
