### PR TITLE
Fix button state change on quickly clicking restart button

### PR DESCRIPTION
**Pull request by ErikHellman**
See #1036

### CODE REVIEW

**Review by samdutton — APPROVED** [review]
LGTM

**Comment by nils-ohlmeier** [comment]
@ErikHellman are you aware that you broke with this change the sample page now for Firefox?

**Comment by ErikHellman** [comment]
@nils-ohlmeier I can't reproduce that error? What version of Firefrox are you using?

**Comment by nils-ohlmeier** [comment]
@ErikHellman the reason you can't repro any more is I believe that your change got reverted in #1078

**Pull request merged**
