### PR TITLE
candidate gathering: use icegatheringstatechange

### PR DESCRIPTION
**Pull request by fippo**
prefers the icegatheringstatechange over the onicecandidate(null)
way of determining whether gathering is done.

Will land in Chrome shortly, supported in Firefox 53+

cc @henbos

### CODE REVIEW

**Comment by aullman** [comment]
Hey @fippo we're having the same issue with Firefox 52 and travis-multirunner. Our tests just started failing, getUserMedia is hanging. Any idea what's going on there?

**Comment by fippo** [comment]
hrm... @jan-ivar any idea?

**Comment by aullman** [comment]
Strangely when I install the same version of Ubuntu on my virtual machine and run travis-multirunner manually things seem to work fine. Not sure what I'm missing.

**Comment by aullman** [comment]
@fippo @jan-ivar Any more thoughts on this? To unblock us I ended up modifying travis-multirunner to let me install a specific browser version and install Firefox 51.0.1 which is obviously not ideal.

**Comment by aiham** [comment]
@fippo @jan-ivar On Travis with Firefox 52, `getUserMedia` does not call either success nor failure callbacks and the test case just times out, even when the timeout is increased to 1 minute. Since it's headless we took a screenshot of the browser using image magick's `import` command and it did not show any pending dialogue or indication of why it's hanging. We could not reproduce this with an Ubuntu VM on our own machine using identical steps to the Travis config. Any ideas?

**Comment by jan-ivar** [comment]
Not sure what's going on. I'm interested in any information that could lead to solving this, such as how to reproduce locally. There's [bug 1345954](https://bugzil.la/1345954), but it's not a regression AFAIK, so it doesn't quite fit as a suspect.

**Comment by aiham** [comment]
FYI @jan-ivar adding pulseaudio like #885 fixed FF52 for us.

**Comment by KaptenJansson** [comment]
LGTM

**Pull request merged**
