### PR TITLE
Update DTMF sample to spec, to work w/Firefox Beta.

### PR DESCRIPTION
**Pull request by jan-ivar**
**Description**
Update DTMF sample to spec, taking advantage of new adapter polyfill in https://github.com/webrtc/adapter/pull/434.

**Purpose**
Update samples to spec; make them work with Firefox Beta.

### CODE REVIEW

**Comment by jan-ivar** [comment]
The [test error](https://travis-ci.org/webrtc/samples/jobs/198414708#L928
) here seems unrelated:
> \# PeerConnection restart ...
>  not ok 37 address changed during ICE restart

@KaptenJansson Next steps?

**Comment by KaptenJansson** [comment]
@jan-ivar working on fixing it and yes this PR is unrelated to that error.

**Comment by jan-ivar** [comment]
@KaptenJansson Ping. How's it going with merging this? Sorry to push, but we have a blog on DTMF in Firefox Beta that's blocked on this (it points to webrtc samples and encourages people to try it out).

**Comment by KaptenJansson** [comment]
Sorry for missing this. LGTM

**Pull request merged**
