### PR TITLE
Add VideoStats HUD element.

### PR DESCRIPTION
**Pull request by juberti**
fpsmeter

Derived from mrdoob's stats.js.

Usage:
- Create VideoStats
- add to DOM using stats.domElement
- call stats.start(videoElement)
- Will display resolution and a framerate graph for that video element.

@samdutton @fippo @jiayl PTAL

### CODE REVIEW

**Comment by KaptenJansson** [comment]
So what's the plan for this?

**Comment by juberti** [comment]
I have a new version I am working on that is more flexible.

**Comment by KaptenJansson** [comment]
Are you going to push it to this pull request or make a new one?

**Comment by KaptenJansson** [comment]
Any news on this?

**Pull request closed without merging**
