### PR TITLE
Make this work with modern autoplay policies.

### PR DESCRIPTION
**Pull request by mounirlamouri**
This sample is broken with browsers implemented modern autoplay policies. This should fix it.

### CODE REVIEW

**Comment by fippo** [comment]
(don't worry about the lint failures, #1238 deals with that as a drive-by fix)

**Comment by mounirlamouri** [comment]
@fippo how can the build be re-run?

**Comment by fippo** [comment]
@mounirlamouri doing a pull+rebase on top of origin/gh-pages should fix the errors. After that its a matter of hunting down someone who feels responsible for reviewing and is allowed to merge ;-)

**Comment by mounirlamouri** [comment]
@samdutton @juberti @guidou can one of you merge this?

**Pull request merged**
