### PR TITLE
Handle no file selection

### LINKED ISSUE #706: Filetransfer page hangs up after canceling a selection of file
Steps to reproduce:
1. Open https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Click on "Choose File" and select an empty/non-empty file to transfer
3. After the transfer is complete, click on "Choose File" again
4. This time, hit Cancel in the dialog box

Actual results:
The "Choose File" button gets disabled and there's a JS error in the console 
Uncaught TypeError: Cannot read property 'name' of undefined
The page needs to reloaded to enable filetransfer

Seen in Windows 7/Mac 10.11/Ubuntu 14.04

### PR DESCRIPTION
**Pull request by samdutton**
**Description**

Handle case where no file is selected for transfer. 

For clarity, some minor tweaks to whitespace and linebreaks as well.

**Purpose**

Fixes #706.

### CODE REVIEW

**Comment by samdutton** [comment]
@alvestrand ping :)

**Comment by alvestrand** [comment]
Travis doesn't like you: WARNING: Rule doesn't have all its properties in alphabetical order. Assure properties are in alphabetical order (order-alphabetical) Browsers: All

Code LGTM, but can you see if you can make Travis happy?

**Comment by samdutton** [comment]
Thanks Harald.

I've fixed the alphabetical problem in #843 .

**Comment by alvestrand** [comment]
Since the error is on an unrelated file, I'm merging this one.

**Pull request merged**
