### PR TITLE
Allow `stuns:` URIs in the trickle ICE sample

### PR DESCRIPTION
**Pull request by rhansen**
The `stuns` URI scheme is defined in https://www.rfc-editor.org/rfc/rfc7064.html#section-3

### CODE REVIEW

**Review by alvestrand — APPROVED** [review]
Looks good to me. Note that allowing it in the sample is no guarantee of browser support, but being able to enter the URL is required to test that, so it's goodness anyway.

**Comment by fippo** [comment]
iirc the reason we do the filtering and alerting manually is that we don't catch failures to construct the peerconnection - chrome throws when it encounters `stuns:`

**Comment by rhansen** [comment]
I pushed a commit to display the Chrome error.

**Comment by fippo** [comment]
thank you for splitting up the commits nicely too!

**Pull request merged**
