### PR TITLE
Add audio to multiple-relay sample

### PR DESCRIPTION
**Pull request by samdutton**
PR version online at https://samdutton.github.io/webrtc/src/content/peerconnection/multiple-relay.

### CODE REVIEW

**Comment by tomasgunn** [comment]
Great - one more request, can we mute the local video preview?  Just to avoid the unnecessary echo from the local player. Echo from the remote one is fine (and preferred).

**Comment by samdutton** [comment]
> can we mute the local video preview

Added muted attribute to video1.

**Comment by tomasgunn** [comment]
lgtm!

**Comment by fippo** [comment]
can you also add a note in which version this is supported? Maybe only enable the checkbox depending on version but... lets keep things simple.

Awesome @tomasgunn!

**Comment by samdutton** [comment]
Added note in #737.

**Pull request merged**
