### PR TITLE
Create Zip file and update name.

### PR DESCRIPTION
**Pull request by guoweis**

### CODE REVIEW

**Comment by KaptenJansson** [comment]
@guoweis you need to make sure to set the correct email when uploading patches, either use your google.com address or your private github email you used to sign the CLA.

**Comment by guoweis** [comment]
I signed it!

**Comment by KaptenJansson** [comment]
@samdutton @juberti do we want to have a release/ folder in root of the repo? Or should it be named something else?

**Comment by KaptenJansson** [comment]
ping

**Comment by guoweis** [comment]
while you're figuring the release folder out, I'm going to submit another
pull request so you don't need to merge this exact one.

Thanks,
Guowei

**Comment by KaptenJansson** [comment]
I'm going to merge this and we can debate over the folder later.

**Pull request merged**
