### PR TITLE
Fix duplicated codec infomation

### PR DESCRIPTION
**Pull request by dong-heun**
**Description**
When changing the priority of the codec, codec information is duplicated

**Purpose**
remove duplication of codec list.

### CODE REVIEW

**Review by fippo — APPROVED** [review]
Not a typo, I mixed up slice (returns element, does not change array) and splice (removes element)

Thanks for catching this!

(@alvestrand should setParameters validate and throw? :-))

**Comment by fippo** [comment]
"4. Remove any duplicate values in codecs." -- https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-setcodecpreferences
-- so not throwing is ok.

**Comment by dong-heun** [comment]
> "4. Remove any duplicate values in codecs." -- https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-setcodecpreferences
> -- so not throwing is ok.

Thanks for your comments.

So I updated my patch and comments. Please check.

**Comment by fippo** [comment]
ah... I still think its a good idea to actually splice and remove the element even if duplicates are handled. Can you revert that, the first version was fine.

**Comment by dong-heun** [comment]
> ah... I still think its a good idea to actually splice and remove the element even if duplicates are handled. Can you revert that, the first version was fine.

Dear @fippo 
I revert the first version. Please check again.
thanks.

**Review by fippo — APPROVED** [review]

**Review by henbos — APPROVED** [review]

**Pull request merged**
